### ISSUE TITLE
Standard Rendering Parameters issue in modular project

### ISSUE THREAD

**Issue by rolek** [blipson89/Synthesis#57]
This is not a bug, maybe would be an enhancement.

While working with modular project and Standard Rendering Parameters I have found that Synthesis will generate IStandardRenderingParameters in the **first project** it finds usage of that template.
By default, the first project is Foundation.Theming one, and this one is referenced by pretty much all features.

Now imagine scenario, where you create another Foundation.MyProject. Since M is before T in alphabet, the IStandardRenderingParameters will be created in this project, breaking all models in all Features (because not all features will reference MyProject)

I do not know if I explained that correctly :)

The improvement here would be to consider Standard Rendering Parameters similarly to StandardTemplate and provide base in Synthesis namespace ?

**Comment by kamsar** [comment]
Yeah this is a known limitation I'm afraid. You can control it by specifically registering the most base foundation assembly first in the config. Double registrations are ignored so you can have a wildcard that also includes it later.

**Comment by rolek** [comment]
Thanks. If the registration are ignored, this should work.

**Comment by blipson89** [comment]
I'm marking this as won't-fix and moving it to [Leprechaun](https://github.com/blipson89/Leprechaun), as I believe it's a valid enhancement
