### ISSUE TITLE
Can synthesis be used with sitecore version 9?

### ISSUE THREAD

**Issue by FrankIversen** [blipson89/Synthesis#61]
**Do you want to request a *feature* or report a *bug*?** Unknown at this point.

**What is the current behavior?** In the middle of an upgrade to sitecore version 9, getting an error from synthesis: An item with the same key has already been added. I havent looked much into it yet. I wanted to know if Synthesis is expected to work in sitecore version 9? 

**If the current behavior is a bug, please provide the steps to reproduce.** unknown at this point

**What is the expected behavior?**

**Please mention your Sitecore version and Synthesis version.** synthesis 8.2.6, sitecore version 9

**Comment by blipson89** [comment]
Hi @FrankIversen,

I'm testing Synthesis on Sitecore 9 now. Everything seems to be working with the exception of `SitecoreRenderingContext`, as Sitecore seems to have removed a DLL. I'm expecting to release a new version of Synthesis built against the Sitecore 9 binaries within the next couple days.

In the meantime, could you provide me with a bit more information regarding the same key issue? Do you have a stack trace you could provide?

Thanks!

**Comment by FrankIversen** [comment]
![stacktrace synthesis](https://user-images.githubusercontent.com/33311049/32330917-d291444a-bfe1-11e7-94ee-e56625b4efc7.PNG)

I am doing an upgrade from 8.1 update 3 to version 9. I am at step 5 in the upgrade guide. This is where i get the exception. Right now it is simply fixed with a disable on the synthesis config file, and the interface for version 9 is now showing. I have not taken a closer yet.

**Comment by blipson89** [comment]
Is it possible the synthesis config file is being copied to two locations and/or loaded twice?

**Comment by blipson89** [comment]
Hi @FrankIversen - I haven't heard anything from you in a bit. Were you able to resolve the issue? 

I've released an updated version of Synthesis built for Sitecore 9. It's listed under pre-release right now on NuGet

**Comment by FrankIversen** [comment]
Hi

There was indeed a second config file. I checked the solution from before the upgrade it also had two synthesis.config files but apparently that did not constitute a problem in the earlier version. I removed the surplus config and the interface for synthesis is showing now :). Thank you for your help. I will try out the new version tomorrow.

**Comment by blipson89** [comment]
Glad to hear it's fixed! I'm going to close the issue. If you encounter any problems with the Sitecore 9 integration, feel free to open another one :)
