### ISSUE TITLE
Models are generated at drive root regardless of sourceFolder value

### ISSUE THREAD

**Issue by rroman81** [blipson89/Synthesis#64]
**Do you want to request a *feature* or report a *bug*?**
I want to report a *bug*.

**What is the current behavior?**
I have deployed the appropriate the configuration files that came Syntehsis 8.2.6.
I have defined the z.DevSettings.config with the following:

```
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/" xmlns:set="http://www.sitecore.net/xmlconfig/set/">
    <sitecore>
	    <sc.variable name="sourceFolder" value="C:\tfs\sitecore\BHFoundation\DEV\src"/>
    </sitecore>
</configuration>
```
However, the models are generated under the systemdrive root instead.

**If the current behavior is a bug, please provide the steps to reproduce.**

I run the /synthesis.aspx where it reports that a few templates are not synchronized.  Clicking Regenerate, succeeds and report success.

**What is the expected behavior?**
I would expect the files to be generated under the sourceFolder root, or error shown.

**Please mention your Sitecore version and Synthesis version.**

I am using Sitecore 8.2 Update 3 with Synthesis 8.2.6.

**Comment by blipson89** [comment]
Hi @rroman81,

Could you try adding this to your `z.DevSettings.config` file:
```xml
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
    <sitecore>
        <settings>
            <setting name="Synthesis.ModelOutputBasePath">
                <patch:attribute name="value">$(sourceFolder)\</patch:attribute>
            </setting>
        </settings>
    </sitecore>
</configuration>
```

**Comment by rroman81** [comment]
Yep.  That was a good catch. Unsure how that setting got overwritten.  We have a dedicated dev related config file TFS managed that overrides to this, and then "sourceFolder" setting is managed by every developer.  Thank you.

**Comment by blipson89** [comment]
Nice! Glad I could help 😃
