### ISSUE TITLE
Multiple <sites> in the Helix model?

### ISSUE THREAD

**Issue by bakgaard** [blipson89/Synthesis#68]
**Do you want to request a *feature* or report a *bug*?**
A bug, or my lack of understanding.

**What is the current behavior?**
I setup a Helix project, and use the 8.3.0-RC01 NuGet package.

I created a patch to include which templates should be synchronized as such:

```cs
<configuration xmlns:patch="http://www.sitecore.net/xmlconfig/">
	<sitecore>
		<synthesis>
			<providers>

				<!--Templates to include-->
				<templateInputProvider>
					<includedPaths hints="list:AddTemplatePath">
						<sites>/sitecore/Templates/Feature</sites>
						<sites>/sitecore/Templates/Foundation</sites>
						<sites>/sitecore/Templates/Project</sites>
					</includedPaths>
				</templateInputProvider>

				<typeListProvider type="Synthesis.Configuration.ConfigurationTypeListProvider, Synthesis">
					<assemblies hint="list:AddAssembly">
						<DC>Marvel.*</DC>
					</assemblies>
				</typeListProvider>

			</providers>
		</synthesis>
	</sitecore>
</configuration>
```

However, when I publish it, and check ``/sitecore/admin/showconfig.aspx `` I get the following lines:

```config
<includedPaths hint="list:AddTemplatePath" hints="list:AddTemplatePath" patch:source="Synthesis.comic.config">
<sites patch:source="Synthesis.comic.config">/sitecore/Templates/Feature</sites>
</includedPaths>
```

The last two sites are not included.

I tried with the following setup , but that is not valid:
```cs
<sites>
  <site>1</site> 
  <site>2</site>
</sites>
```

How can I add the Helix structure?

**What is the expected behavior?**
I had hoped multiple template folders could be included.

**Please mention your Sitecore version and Synthesis version.**
``Sitecore v. 9.0.171002``, and ``Synthesis 8.3.0-RC01``

**Comment by kamsar** [comment]
Use unique xml tag names for each include. It's a limitation of how
Sitecore parses configs; they are being mashed together.

**Comment by rroman81** [comment]
Yep, that's what @kamsar said. I used the following
``` xml
...
<includedPaths hints="list:AddTemplatePath">
  <Feature>/sitecore/Templates/Feature</Feature>
  <Foundation>/sitecore/Templates/Foundation</Foundation>
  <Project>/sitecore/Templates/Project</Project>
</includedPaths>
...
```
Under typeListProvider, I separate each layer with a specific namespace prefix and thus use the same strategy.

**Comment by bakgaard** [comment]
Oh. That seems obvious in retrospective.

Thank you
