### ISSUE TITLE
Shouldn't Synthesis.Solr.Core depend on Synthesis.Core?

### ISSUE THREAD

**Issue by StefanTBG** [blipson89/Synthesis#70]
We noticed that Synthesis.Solr.Core has a dependency on Synthesis. Shouldn't the only dependency be Synthesis.Core?

We'd like to use Synthesis.Solr.Core in our Helix modules, but we don't want all of the synthesis configs being installed in those modules, especially on the Project layer, which would overwrite what we have in the Foundation layer.

https://github.com/blipson89/Synthesis/blob/c36bb165e4528360fc8cdd9d69ee9a6fe07c7405/Source/Synthesis.Solr/Synthesis.Solr.nuspec#L17

Also, can be seen in the dependencies list in the NuGet gallery: https://www.nuget.org/packages/Synthesis.Solr.Core/8.2.7-RC01

**Comment by blipson89** [comment]
@StefanTBG you are correct. I'll update the dependency and release the change shortly.

**Comment by StefanTBG** [comment]
Great! Thanks!

**Comment by blipson89** [comment]
@StefanTBG 8.2.7-RC02 was just pushed, removing that dependency. It may take NuGet a little bit to update

**Comment by StefanTBG** [comment]
Excellent. Thanks for the fast reply!

**Comment by blipson89** [comment]
No problem! Thanks for catching it
