### ISSUE TITLE
IHyperLinkField RenderWithBody usage

### ISSUE THREAD

**Issue by Chrlol** [blipson89/Synthesis#86]
BeginHyperlinkFor is Obsolete, it says to use RenderWithBody instead.
I have been unable to find any examples of usage anywhere, can someone provide me with an example of usage?

**Comment by blipson89** [comment]
```cshtml
@using (Model.<linkfield name>.RenderWithBody(Html))
{
    <span>
        @Model.<linkfield name>.Text
    </span>
}
```
