### ISSUE TITLE
Can't keep customer or partner name in naming helix projects (project namespace) as Synthesis.model.cs throws error

### ISSUE THREAD

**Issue by PaulsonMac** [blipson89/Synthesis#88]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?** 
Building solution fails due to error in Synthesis,model.cs

**If the current behavior is a bug, please provide the steps to reproduce.**
1. For e.g.  Keep the project name as "MyCustomerName.Feature.Maps"
2. Configure Synthesis
3. Build solution
3. Error in Sitecore namespace wherever its subclasses are used (see attached error screenshot)

**What is the expected behavior?**
Synthesis,model.cs should build successfully without error

**Please mention your Sitecore version and Synthesis version.**
Sitecore 9.3 & Synthesis 9.1.0.2

![image](https://user-images.githubusercontent.com/42689728/85193479-90d01680-b2e6-11ea-84ed-f4a224ed9363.png)

**Comment by PaulsonMac** [comment]
Example of some Sitecore classes where errors are thrown

![image](https://user-images.githubusercontent.com/42689728/85193720-c0801e00-b2e8-11ea-81f1-b784b8098922.png)

![image](https://user-images.githubusercontent.com/42689728/85193789-f45b4380-b2e8-11ea-99bf-e3a8ef336b69.png)

**Comment by PaulsonMac** [comment]
These error were also thrown in my cs classes, but I added namespace "using Sitecore;" or by adding alias.. But since Synthesis.model.cs is an auto-generated class how to resolve this and get my build successful..?!

Am I'm missing something here..

**Comment by blipson89** [comment]
@PaulsonMac based off where the red squiggly lines are, it looks like whatever `csproj` the `Synthesis.Model.cs` file is in is missing a reference to `Sitecore.Kernel` and `Sitecore.ContentSearch`.

**Comment by PaulsonMac** [comment]
Thanks very much for your reply :)
I already tried adding `Sitecore.Kernel` and `Sitecore.ContentSearch` as a reference to that project, but it is not adding these references but VS simply throws the below error : 

![image](https://user-images.githubusercontent.com/42689728/85256405-ceb57200-b481-11ea-8409-3371fe8bb0ae.png)

**Comment by PaulsonMac** [comment]
I also tried adding `Sitecore.ContentSearch` as  a nuget package, but same error persists

**Comment by royvou** [comment]
Is it possible you use "sitecore" in your namespace?

**Comment by PaulsonMac** [comment]
I can try to consider adding "Sitecore.xyz.xyz" as my project name. But before considering, I want to know whether it is not possible to use Synthesis unless we have "Sitecore." at the beginning of the namespace/project name..? If there is no other solution to fix this issue, then I can try considering it..

**Comment by PaulsonMac** [comment]
But having "Sitecore." in my namespace always fixes the error. As described in this issue name, I'm not able to keep Customer/Partner name in the beginning of the namespace

**Comment by blipson89** [comment]
hey @PaulsonMac - I ping'd you on Sitecore slack a few days ago asking for a bit more information in a DM

**Comment by PaulsonMac** [comment]
Hi Ben! I'm sorry.. this issue was fixed by my team leader. I think I missed renaming the project name in some place.. So, this issue is fixed for me..
