### ISSUE TITLE
Access Denied message even though logged into Sitecore

### ISSUE THREAD

**Issue by unstab1e** [blipson89/Synthesis#90]
Issue I am currently having.

VS solution outside of webroot. I have used Synthesis before several times. Believe that I have config files set up properly. Using IdentityServer. When logged into Sitecore as admin, when I attempt to run the synthesis.aspx page I get an "Access Denied - You may need to sign in to Sitecore as an Administrator" message.

Synthesis will indicate number of differences and allow to sync.

Sitecore version 10.0, Synthesis version 9.1.0.2

**Comment by blipson89** [comment]
Hi @unstab1e 

did you remove the `.disabled` extension from this file:

https://github.com/blipson89/Synthesis/blob/master/Source/Synthesis/Standard%20Config%20Files/Synthesis.ControlPanel.IdentityServer.config.disabled

**Comment by unstab1e** [comment]
When I pulled Synthesis into my VS project using Nuget, this file did not come down with it. I manually added the .Config file and now Synthesis syncs.

Thank you.

**Comment by blipson89** [comment]
glad to hear it!
