### ISSUE TITLE
Synthesis 9.1.0.2 in Sitecore 9.3

### ISSUE THREAD

**Issue by dev810vm** [blipson89/Synthesis#91]
New to Synthesis... We're working on a Sitecore 9.3 upgrade with code that relied on Synthesis 8.2.6 and I can't get Synthesis to load. I installed the Nuget packages for Synthesis, Synthesis.Core, Synthesis.MVC & SynthesisMVC.Core 9.1.0.2, updated the config files in the include/Synthesis folder and it's not working. I checked showconfig.aspx for the 9.3 instance and none of the Synthesis configs are patched in and synthesis.aspx is 404ing. Any assistance would be greatly appreciated. Thanks

**Comment by blipson89** [comment]
Hi @dev810vm - are you using the `PackageReference` NuGet method now, and you weren't previously?

`PackageReference` isn't too friendly when it comes to deploying config files in non .NETCore apps. If you're using PackageReference, you'll want to add the config files directly to a project (I usually put it in `Foundation.Orm` or something similar).

Here are links to the config files:
1. [Synthesis base config files (9.1.0.2)](https://github.com/blipson89/Synthesis/tree/9.1.0.2/Source/Synthesis/Standard%20Config%20Files)
1. [Synthesis.Mvc config file (9.1.0.2)](https://github.com/blipson89/Synthesis/tree/9.1.0.2/Source/Synthesis.Mvc/Standard%20Config%20Files)
1. [Synthesis.Solr config file (9.1.0.2)](https://github.com/blipson89/Synthesis/tree/9.1.0.2/Source/Synthesis.Solr/Standard%20Config%20Files)

You can alternatively grab the files directly from the NuGet package, but it's easier for me to just link it from Github 🙂 

This is unfortunately a limitation of PackageReference and there's not much I can do to get around it.

Thanks,
Ben

**Comment by dev810vm** [comment]
Thanks Ben, I don't think we're using the PackageReference method. I did have all of the configs in the project and in the Synthesis folder in the Include folder except for the Solr one. I added that and there's no change. The only reference to Synthesis I see in Sitecore anywhere is the log file when it lists all of the loaded dll's. No errors/no patch files loaded

c:\inetpub\wwwroot\slhn\website\bin\synthesis.dll (Synthesis, Sitecore object mapping framework, 9.1.0.2)
c:\inetpub\wwwroot\slhn\website\bin\synthesis.mvc.dll (Synthesis, Sitecore object mapping framework, 9.1.0.2)

Thanks, Jim

**Comment by dev810vm** [comment]
App_Config\Include\Synthesis

Thanks, Jim

**Comment by blipson89** [comment]
That's really weird. That should be the correct location. You said "No errors/no patch files loaded" - does that mean you've checked `http://<yoursite>/sitecore/admin/showconfig.aspx` and searched for the word "Synthesis" and it wasn't anywhere?

Thanks,
Ben

**Comment by dev810vm** [comment]
Yup, I've checked showconfig.aspx and there's no reference to synthesis. I do have some Solr errors in the logs files, could something like that stop them from being loaded?

**Comment by blipson89** [comment]
Solr errors likely couldn't stop them from being loaded. If "synthesis" isn't showing up anywhere in the `/showconfig.aspx`, it means Sitecore isn't seeing the files for some reason. Try putting the config files in a different folder - one with other config files that you _know_ are loading.

**Comment by dev810vm** [comment]
Wanted to update this item. The Synthesis configs were not being added due to an issue with the Layers.config file in Sitecore. Thanks for your help.

**Comment by blipson89** [comment]
Ohhh! That makes sense. 
Glad it's all sorted!
